### ISSUE TITLE
Serial Monitor on Arduino Due

### ISSUE THREAD

**Issue by Serray** [engineertype/MAX31856#3]
Hi.

Creating the Thermocouple Object prevents the communication with the serial monitor. If i delete this part, it works fine. Im using an Arduino Die.

**Comment by Serray** [comment]
Arduino Due

**Comment by engineertype** [comment]
Sounds like you're sharing some pins between the thermocouple and the serial port.  Try using different pins

**Comment by Serray** [comment]
I used an other library now,
with it it is working.
So its definetly not up to my Hardware.
